name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule: [cron: "12 */24 * * *"]
  
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  
  
jobs:
  build-and-simulate:
    name: Build and Simulate
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: build and simulate
        run : |
          ./setup.sh
          ./run.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3